modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "databox"
version = "${file.jarVersion}"
displayName = "databox"
logoFile = "databox.png"
authors = "dannbrown"
description = '''
Forge Template with ParchmentMC, KotlinForForge and Mixin
'''

[[dependencies.databox]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.databox]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
